version: "3.9"

services:
  web:
    build: ./docker/nginx
    container_name: nginx_estat
    depends_on:
      - drupal
    ports:
      - "80:80"
    links:
      - "drupal:dp"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
  drupal:
    build: ./docker/drupal
    container_name: drupal
    volumes:
      - ./app:/var/www/html
      - ./docker/drupal/config/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql_estat
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - ./docker/mysql/db:/var/lib/mysql
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
