<?php

/**
 * @file
 * HelloWorldモジュールの主要なファイル。
 *
 * このファイルは、HelloWorldモジュールの主要な機能とフック実装を含んでいます。
 * Drupal内でカスタムページを表示し、特定の機能を提供する方法を実装する例を提供します。
 */

/**
 * @defgroup helloworld_example HelloWorld: 例
 * @ingroup examples
 * @{
 * このドキュメンテーショングループは、HelloWorldモジュールの使用例を示しています。
 * Drupal内でカスタムページを表示する方法やカスタムテーマフックの実装例を提供します。
 * これは、Drupal内でカスタムモジュールを作成する際の基本的なパターンを示しています。
 */

/**
 * hook_theme()の実装。
 *
 * この関数は、モジュールで使用される複数のテーマフックを定義します。
 * 各テーマフックは、特定のテンプレートと関連付けられ、変数をテンプレートに渡すことができます。
 */
function helloworld_theme($existing, $type, $theme, $path) {
  return [
    'my-template' => [
      'variables' => ['variables' => NULL],
    ],
    'contact-template' => [
      'variables' => ['variables' => NULL],
    ],
    'contact-display-template' => [
      'variables' => ['variables' => NULL],
    ],
    'contact-edit-template' => [
      'variables' => ['variables' => NULL],
    ],
    'tab-template' => [
      'variables' => ['variables' => NULL],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function helloworld_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // DiceForm.php に対応するフォームIDを確認します。
  if ($form_id == 'helloworld_dice_form') {
    // 既存のフォーム要素を取得します。
    $form_elements = &$form;

    // フォームの先頭にメッセージを追加します。
    $form_elements['dice_game_message'] = [
      '#type' => 'item',
      '#markup' => '<p>これはサイコロゲームです。</p>',
      '#weight' => -10, // フォーム内の要素の表示順を調整する場合に使用します。
    ];
  }
}

/**
 * @} End of "defgroup helloworld_example".
 */