<?php

/**
 * @file
 * HelloWorldモジュールの主要なファイル。
 *
 * このファイルは、HelloWorldモジュールの主要な機能とフック実装を含んでいます。
 * Drupal内でカスタムページを表示し、特定の機能を提供する方法を実装する例を提供します。
 */

/**
 * @defgroup helloworld_example HelloWorld: 例
 * @ingroup examples
 * @{
 * このドキュメンテーショングループは、HelloWorldモジュールの使用例を示しています。
 * Drupal内でカスタムページを表示する方法やカスタムテーマフックの実装例を提供します。
 * これは、Drupal内でカスタムモジュールを作成する際の基本的なパターンを示しています。
 */

/**
 * hook_theme()の実装。
 *
 * この関数は、モジュールで使用される複数のテーマフックを定義します。
 * 各テーマフックは、特定のテンプレートと関連付けられ、変数をテンプレートに渡すことができます。
 */
function helloworld_theme($existing, $type, $theme, $path) {
  return [
    'my-template' => [
      'variables' => ['test_var' => NULL],
    ],
    'contact-template' => [],
    'contact-display-template' => [
      'variables' => ['contacts' => NULL],
    ],
    'contact-edit-template' => [
      'variables' => ['contact' => NULL],
    ],
    'tab-template' => [],
  ];
}

/**
 * @} End of "defgroup helloworld_example".
 */