<?php

/**
 * @file
 * 開発者向けの例のためのモジュールファイル。
 * このファイルは、@link http://drupal.org/project/examples Examples for Developers Project @endlink
 * にある多くの例のモジュールのスタブファイルとして機能します。
 * これらのモジュールはダウンロードして実験することができます。
 * examples.module は、ドキュメントの例と言えるかもしれません。ただし、
 * 例のサブモジュールでは多くの Doxygen グループが定義されていることに注意してください。
 * これは他のモジュールにとって適切な戦略であるかどうかは、また別の問題です。
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Url;

/**
 * @defgroup examples Examples
 * @{
 * 幅広いDrupalコア機能のための十分に文書化されたAPIの例。
 * 開発者は、例を実験して素早く特定のAPIの使用方法を学ぶことができ、
 * 自分の利用に適応させることができます。
 * Examples for Developers Projectをダウンロードして（提出、バグレポート、パッチ、ドキュメントで参加してください）
 * http://drupal.org/project/examples
 */

/**
 * hook_toolbar() を実装します。
 */
function examples_toolbar() {
  // まず、すべての例のモジュールとそれらのルートの配列を構築します。
  // 各例を汚さないように、このハードコーディングされた方法に頼ります。
  $examples = _examples_toolbar_routes();

  // メニューのリンクのリストを構築します。
  $links = [];
  foreach ($examples as $module => $route) {

    // モジュールがインストールされているかどうかを確認します。
    if (\Drupal::moduleHandler()->moduleExists($module)) {

      // Drupalからモジュールの情報（タイトル、説明）を取得します。
      $info = \Drupal::service('extension.list.module')->getExtensionInfo($module);

      // 情報がない場合、例が有効になっていないため、表示しません。
      if (!empty($info)) {
        $links[$module] = [
          'title' => Html::escape($info['name']),
          'url' => Url::fromRoute($route),
          'attributes' => [
            'class' => [Html::getClass($module)],
            'title' => Html::escape($info['description']),
          ],
        ];
      }
    }
  }

  // Add a link to enable all examples.
  $links['enable_examples'] = [
    'title' => t('Enable Examples'),
    'url' => Url::fromRoute('system.modules_list'),
    'options' => [
      'title' => t('Enable more examples in on the Extend page.'),
    ],
    'fragment' => 'edit-modules-example-modules',
  ];

  // Create the examples toolbar render array.
  $items['examples'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Examples'),
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => [
        'title' => t('Developer Examples'),
        'class' => ['toolbar-icon', 'toolbar-icon-examples'],
      ],
    ],
    'tray' => [
      '#heading' => t('Developer Examples'),
      'shortcuts' => [
        '#theme' => 'links__toolbar_example',
        '#links' => $links,
        '#attributes' => [
          'class' => ['toolbar-menu'],
        ],
      ],
    ],
    '#weight' => 99,
    '#attached' => [
      'library' => [
        'examples/examples.icons',
      ],
    ],
  ];

  return $items;
}

/**
 * ツールバールのルートをテストするためのツールバーのリンクのリストを取得します。
 * この関数は、キーをルートを提供するモジュール名とし、ツールバーのルートのキー付き配列を返します。内部でのみ使用されます。
 * @return string[]
 *   ツールバーのルートのキー付き配列。
 * @see toolbar_menu()
 */
function _examples_toolbar_routes() {
  return [
    'ajax_example' => 'ajax_example.description',
    'batch_example' => 'batch_example.form',
    'block_example' => 'block_example.description',
    'cache_example' => 'cache_example.description',
    'config_entity_example' => 'entity.robot.list',
    'content_entity_example' => 'entity.content_entity_example_contact.collection',
    'cron_example' => 'cron_example.description',
    'dbtng_example' => 'dbtng_example.generate_entry_list',
    'email_example' => 'email_example.description',
    'events_example' => 'events_example.description',
    'field_example' => 'field_example.description',
    'field_permission_example' => 'field_permission_example.description',
    'file_example' => 'file_example.fileapi',
    'form_api_example' => 'form_api_example.description',
    'hooks_example' => 'hooks_example.description',
    'js_example' => 'js_example.info',
    'menu_example' => 'examples.menu_example',
    'node_type_example' => 'config_node_type_example.description',
    'page_example' => 'page_example.description',
    'pager_example' => 'pager_example.page',
    'phpunit_example' => 'phpunit_example.description',
    'plugin_type_example' => 'plugin_type_example.description',
    'queue_example' => 'queue_example.form',
    'render_example' => 'render_example.description',
    'session_example' => 'session_example.form',
    'stream_wrapper_example' => 'stream_wrapper_example.description',
    'tabledrag_example' => 'tabledrag_example.description',
    'tablesort_example' => 'tablesort_example.description',
    'testing_example' => 'testing_example.description',
    'tour_example' => 'tour_example.description',
  ];
}

/**
 * @} 'defgroup examples' の終わり。
 */